CREATE TABLE USERS (
    id  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    username varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id));