CREATE TABLE DOCUMENTS (
  id  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  number INTEGER NOT NULL,
  date DATE NOT NULL,
  total FLOAT,
  CONSTRAINT documents_pk PRIMARY KEY (id));