CREATE TABLE USER_ROLES (
  id  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  user_id INTEGER,
  role_id INTEGER,
  CONSTRAINT role_id_ref FOREIGN KEY (role_id) REFERENCES ROLES(id),
  CONSTRAINT user_id_ref FOREIGN KEY (user_id) REFERENCES USERS(id));